Update syntax-checker.yml

diff --git a/.github/workflows/syntax-checker.yml b/.github/workflows/syntax-checker.yml
--- a/.github/workflows/syntax-checker.yml
+++ b/.github/workflows/syntax-checker.yml
@@ -30,8 +30,11 @@ jobs:
       - name: Check components JSON syntax
         id: check-components
         run: |
-            for file in $PWD/${{ inputs.pathToFiles }}/components/${{ inputs.application }}/*.json; do
-            jq . "$file" 1> /dev/null
+            for file in "$PWD"/${{ inputs.pathToFiles }}/components/${{ inputs.application }}/*.json; do
+              if ! jq . "$file" 1> /dev/null; then
+                echo "Error in $file"
+                exit 1
+              fi
             done
 
       - name: Final step
